import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./styles/globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quicksandFont = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACM@SFSU",
  icons: "/assets/logos/avatar-logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Head>
          {/* Add metadata */}
          <title>
            <title>{metadata.title?.toString()}</title>
          </title>
          <meta name="description" content={metadata.description?.toString()} />
          <link rel="icon" href={metadata.icons?.toString()} />
          <link rel="shortcut icon" href={metadata.icons?.toString()} />
          <link rel="apple-touch-icon" href={metadata.icons?.toString()} />
        </Head>
      </head>

      <body
        className={`${quicksandFont.variable} ${geistMono.variable} antialiased `}
      >
        {children}
        <footer className="text-center p-6 mt-8">
          <div className="space-x-6">
            <a
              href="https://discord.gg/your-link"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xl"
            >
              <i className="fab fa-discord"></i>
            </a>
            <a
              href="https://instagram.com/your-profile"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xl"
            >
              <i className="fab fa-instagram"></i>
            </a>
            <a
              href="https://www.linkedin.com/company/your-company"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xl"
            >
              <i className="fab fa-linkedin"></i>
            </a>
            <a
              href="mailto:contact@yourdomain.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xl"
            >
              <i className="fas fa-envelope"></i>
            </a>
            <a
              href="https://yourwebsite.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xl"
            >
              <i className="fas fa-globe"></i>
            </a>
          </div>
          <p className="text-sm mt-4">
            &copy; 2025 ACM@SFSU. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
